### General settings.
## The name of singer
spk: "JA-Soprano-1"

## exp tag(for managing experiments)
tag:

## Directory of Unzipped singing voice database
# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "/home/ilias/Documents/GTSinger/"

## Output directory
# All the generated labels, intermediate files, and segmented wav files
# will be saved in the following directory
out_dir: "./data"

## Songs to be excluded from training.
exclude_songs: []

### Pyinsy related settings.
## Sinsy dictionary directory
sinsy_dic: "../../_common/no2/dic"
